web/controllers/AccountController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use app\models\User;
use app\models\UserProfile;
use app\models\search\SearchWish;
use app\models\Message;
use app\models\Wish;
use app\models\FriendRequest;
use app\models\FollowRequest;

class AccountController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['edit-account','my-account','inbox'],
                'rules' => [
                    [
                        'actions' => ['edit-account','my-account','inbox'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }
	
    public function actionProfile($id){
		if($id==\Yii::$app->user->id)
			return $this->redirect('my-account');
		$user = User::findOne($id);
		$profile = UserProfile::find()->where(['user_id'=>$id])->one();
		
        $searchModel = new SearchWish();
        $dataProvider = $searchModel->searchUserWishes(Yii::$app->request->queryParams,$id,'active');
		
		return $this->render('other_profile', [
            'user' => $user,
			'profile' => $profile,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);		
    }
    public function actionMyAccount(){
		
        $user = User::findOne(\Yii::$app->user->id);
        $profile = UserProfile::find()->where(['user_id'=>\Yii::$app->user->id])->one();
		
        $searchModel = new SearchWish();
        $dataProvider = $searchModel->searchUserWishes(Yii::$app->request->queryParams,\Yii::$app->user->id,'active');
		
        return $this->render('profile', [
            'user' => $user,
            'profile' => $profile,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);		
    }
	
    public function actionMyFullfilled($id=null){
        if(!$id)
            $id = \Yii::$app->user->id;
        
        $user = User::findOne($id);
        $profile = UserProfile::find()->where(['user_id'=>$id])->one();
		
        $searchModel = new SearchWish();
        $dataProvider = $searchModel->searchUserWishes(Yii::$app->request->queryParams,$id,'fullfilled');
        $dataProvider2 = $searchModel->searchUserWishes(Yii::$app->request->queryParams,$id,'fullfilledGrant');
        
        if($id == \Yii::$app->user->id)
            return $this->render('my_fullfilled', [
                'user' => $user,
                'profile' => $profile,
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
                'dataProvider2' => $dataProvider2,
            ]);	
        else
            return $this->render('other_fullfilled', [
                'user' => $user,
                'profile' => $profile,
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);			
    }
    
    public function actionMySaved($id=null){
		if(!$id)
			$id = \Yii::$app->user->id;		
		$user = User::findOne($id);
		$profile = UserProfile::find()->where(['user_id'=>$id])->one();
		
        $searchModel = new SearchWish();
        $dataProvider = $searchModel->searchSavedWishes(Yii::$app->request->queryParams,\Yii::$app->user->id);
		
		return $this->render('my_saved', [
            'user' => $user,
			'profile' => $profile,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);			
	}
	
    public function actionMyProgress(){
		
        $user = User::findOne(\Yii::$app->user->id);
        $profile = UserProfile::find()->where(['user_id'=>\Yii::$app->user->id])->one();
		
        $searchModel = new SearchWish();
        $dataProvider = $searchModel->searchProcessWishes(Yii::$app->request->queryParams,\Yii::$app->user->id,'active');
	$dataProvider2 = $searchModel->searchProcessWishes(Yii::$app->request->queryParams,\Yii::$app->user->id,'inprogressGrant');
        
        return $this->render('my_progress', [
            'user' => $user,
            'profile' => $profile,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'dataProvider2' => $dataProvider2,
        ]);		
    }
	
    public function actionScrollMyActive($page)
    {
        $searchModel = new SearchWish();
        $dataProvider = $searchModel->searchUserWishes(Yii::$app->request->queryParams,\Yii::$app->user->id,'active');

        $dataProvider->pagination->page = $page;
        $str = '';
        foreach($dataProvider->models as $wish){
            $str .= $wish->wishAsCard;
        }
        return $str;
    }
    
    public function actionScrollMySaved($page)
    {
        $searchModel = new SearchWish();
        $dataProvider = $searchModel->searchSavedWishes(Yii::$app->request->queryParams,\Yii::$app->user->id);

        $dataProvider->pagination->page = $page;
        $str = '';
        foreach($dataProvider->models as $wish){
            $str .= $wish->wishAsCard;
        }
        return $str;
    }
	
	public function actionEditAccount()
	{	
            $id = \Yii::$app->user->id;
            $user = User::findOne(\Yii::$app->user->id);

            $profile = UserProfile::find()->where(['user_id'=>\Yii::$app->user->id])->one();
            $countries = \yii\helpers\ArrayHelper::map(\app\models\Country::find()->orderBy([new \yii\db\Expression('FIELD (id, 231) DESC')])->addOrderBy('name ASC')->all(),'id','name');
            $states = \yii\helpers\ArrayHelper::map(\app\models\State::find()->where(['country_id'=>$profile->country])->all(),'id','name');	
            $cities = \yii\helpers\ArrayHelper::map(\app\models\City::find()->where(['state_id'=>$profile->state])->all(),'id','name');	

            $user->scenario = 'updatecheck';
            $current_image = $profile->profile_image;

            if (($user->load(Yii::$app->request->post())  && $user->validate()) && $profile->load(Yii::$app->request->post())){
		
                if($user->password)
                    $user->setPassword($user->password);
                
                $user->updated_at = date("Y-m-d H:i:s");
                
                if($user->save()){	
                    $profile->user_id = $user->id;
                    $profile->save_id       =   1;
                    
                    if(empty(Yii::$app->request->post()['UserProfile']['profile_image']))
                    {
                        if(empty($profile->dulpicate_image))
                        {
                            $profile->profile_image =   'images/img1.jpg';
                        }
                        else if(!empty($profile->dulpicate_image) && $profile->dulpicate_image != $current_image )
                        {
                            $profile->profile_image = $profile->dulpicate_image;
                        } else {
                            $profile->profile_image = $current_image;
                        }
                    }
                    else
                    {
                        if($current_image !== Yii::$app->request->post()['UserProfile']['profile_image'])
                        {
                            $data   =   Yii::$app->request->post()['UserProfile']['profile_image'];
                            list($type, $data) = explode(';', $data);
                            list(, $data)      = explode(',', $data);
                            $data = base64_decode($data);
                            file_put_contents('web/uploads/users/'.$profile->user_id.'.jpg', $data);

                            $profile->profile_image =   $profile->user_id.'.jpg';
                            $profile->save_id       =   0;
                        }
                        else
                        {
                            if(! empty($profile->dulpicate_image))
                                $profile->profile_image = $profile->dulpicate_image;
                            else
                                $profile->profile_image = $current_image;
                        }
                    }
                    
                    $profile->save();
                    $profile->sendProfileEmail(\Yii::$app->user->id);		
                    /* \Yii::$app->getSession()->setFlash('success', 'Account details have been changed successfully');
                    return $this->redirect('my-account'); */

                    \Yii::$app->getSession()->setFlash('success', 'Account details have been changed successfully');
                    return $this->redirect(['site/index-home']);
		}
            }		
            else 
            { 	
                return $this->render('my_account', [
                            'user' => $user,
                            'profile' => $profile,
                            'countries' => $countries,
                            'states' => $states,
                            'cities' => $cities
                    ]);
            }
	}
	
	public function actionSendMessage(){
		
            $from = \Yii::$app->request->post()['send_from'];
            $to = \Yii::$app->request->post()['send_to'];
            $msg = \Yii::$app->request->post()['msg'];

            if($from != '' && $to != '' && $msg != ''){
                    $message = new Message();
                    $message->sender_id = $from;
                    $message->recipient_id = $to;
                    $message->parent_id = 0;
                    $message->text = $msg;
                    $message->created_at = date("Y-m-d H:i:s");
                    if($message->save()){
                            Yii::$app->session->setFlash('messageSent');
                    }
                            return $this->redirect(['profile','id'=>$to]);
            }
	}
	
	
	public function actionSendMessageWishes(){
		

web/controllers/PageController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Page;
use app\models\search\SearchPage;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PageController implements the CRUD actions for Page model.
 */
class PageController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Page models.
     * @return mixed
     */
    public function actionIndex()
    {
		if(!Yii::$app->user->isGuest && \Yii::$app->user->identity->role == 'admin'){
			$searchModel = new SearchPage();
			$dataProvider = $searchModel->search(Yii::$app->request->queryParams);

			return $this->render('index', [
				'searchModel' => $searchModel,
				'dataProvider' => $dataProvider,
			]);
		}else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Displays a single Page model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Page model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
		if(!Yii::$app->user->isGuest && \Yii::$app->user->identity->role == 'admin'){
			$model = new Page();

			if ($model->load(Yii::$app->request->post()) && $model->save()) {
				return $this->redirect(['view', 'id' => $model->p_id]);
			} else {
				return $this->render('create', [
					'model' => $model,
				]);
			}
		}else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Updates an existing Page model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
		if(!Yii::$app->user->isGuest && \Yii::$app->user->identity->role == 'admin'){
			$model = $this->findModel($id);

			if ($model->load(Yii::$app->request->post()) && $model->save()) {
				if($model->p_id ==  4)
				return $this->redirect(['site/about', 'id' => $model->p_id]);
				else
				return $this->redirect(['view', 'id' => $model->p_id]);
			
			} else {
				return $this->render('update', [
					'model' => $model,
				]);
			}
		}else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Deletes an existing Page model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
/*     public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    } */

    /**
     * Finds the Page model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Page the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Page::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

web/views/site/about.php
<?php 
use yii\helpers\Url;
use app\models\UserProfile;
use yii\helpers\Html;

$this->title = 'About Us';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about smp-mg-bottom">
    <h3 class="fnt-skyblue" ><?= Html::encode($this->title) ?></h3>
    <?php if(!Yii::$app->user->isGuest && \Yii::$app->user->identity->role == 'admin'){?>
    <p>
        <?= Html::a('Update', ['page/update', 'id' => $model->p_id], ['class' => 'btn btn-primary']) ?>
    </p>
    <?php } ?>
    <p>
        SimplyWishes.com was founded with the purpose of creating a community where people help each other to realize their dreams. Browse through our site and help someone’s wish become a reality or post a wish yourself and let us connect you with people that can help make your dream come true.
    </p>
    <div class="row">
        <div class="col-md-6" style="overflow:auto;"><img class="img-responsive aboutImage" src="<?= Yii::$app->homeUrl?>web/images/about.jpg" width="230"></div>
        <div class="col-md-6"><?= $model->content?></div>
    </div>
</div>

<!--------------- SLIDER CHECK Function ---------------------->
  <link rel="stylesheet" type="text/css" href="<?= Yii::$app->homeUrl?>web/src/slick/slick.css">
  <link rel="stylesheet" type="text/css" href="<?= Yii::$app->homeUrl?>web/src/slick/slick-theme.css"> 
  <script src="<?= Yii::$app->homeUrl?>web/src/slick/jquery-2.2.0.min.js" type="text/javascript"></script>
  <script src="<?= Yii::$app->homeUrl?>web/src/slick/slick.js" type="text/javascript" charset="utf-8"></script>
  
  
  
  <script type="text/javascript">
  var js = $.noConflict();
   js(document).on('ready', function() {
      js(".regular").slick({
         dots: false,
	 infinite: true,
	 speed: 300,
	 slidesToShow: 5,
	 slidesToScroll: 1,
	 responsive: [
		{
		 breakpoint: 1024,
		 settings: {
			slidesToShow: 3,
			slidesToScroll: 1,
			infinite: true,
			dots: false
		 }
		},
		{
		 breakpoint: 600,
		 settings: {
			slidesToShow: 2,
			slidesToScroll: 1
		 }
		},
		{
		 breakpoint: 480,
		 settings: {
			slidesToShow: 1,
			slidesToScroll: 1
		 }
		}
	 ]
      });
     
	 
    });
  </script>
  
 
  
  <!--------------- SLIDER CHECK Function END ---------------->
 

web/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact Us';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h3 class="fnt-skyblue"><?= Html::encode($this->title) ?></h3>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')){ ?>

        <div class="alert alert-success">
            Thanks For Contcting Us. We will Reach you Very Soon.
        </div>

    <?php } ?>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true])->label("Name <span class='valid-star-color' >*</span> ") ?>

                    <?= $form->field($model, 'email')->label("Email <span class='valid-star-color' >*</span> ") ?>

                    <?= $form->field($model, 'phone_number')->label("Phone Number <span class='valid-star-color' >*</span> "); ?>
					
                    <?= $form->field($model, 'subject')->label("Subject <span class='valid-star-color' >*</span> ") ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6])->label("Body <span class='valid-star-color' >*</span> ") ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ])->label("Verification Code <span class='valid-star-color' >*</span> ") ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

   
</div>

web/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h3><?= Html::encode($this->title) ?></h3>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

web/views/site/index.php
<?php 
use yii\helpers\Url;
?>
<div class='intro_text'>
    <p class="homeIntroText">Make a Wish and Post it. Grant a Wish and Make Someone Happy. <br>Contribute to our Forum and Be Heard.</p>
    <div class='row intro_videos'>
        <div class="col-md-4 homeWishTpl">
            <a href="<?=Yii::$app->homeUrl?>editorial/editorial-page?id=6&class=video">
                <img class='img-responsive' src="<?=Yii::$app->homeUrl?>web/uploads/editorial/Connect_Thumb_V2.jpg "/>
                <span class='glyphicon glyphicon-play-circle'></span>
            </a>
        </div>
        <div class="col-md-4 homeWishTpl">
            <a href="<?=Yii::$app->homeUrl?>editorial/editorial-page?id=5&class=video">
                <img class='img-responsive' src="<?=Yii::$app->homeUrl?>web/uploads/editorial/Do You Have A Wish_Thumb.png"/>
                <span class='glyphicon glyphicon-play-circle'></span>
            </a>
        </div>
        <div class="col-md-4 homeWishTpl">
            <a href="<?=Yii::$app->homeUrl?>editorial/editorial-page?id=4&class=video">
                <img class='img-responsive' src="<?=Yii::$app->homeUrl?>web/uploads/editorial/Social Networking Thumb.png"/>
                <span class='glyphicon glyphicon-play-circle'></span>
            </a>
        </div>
    </div>
</div>

<div class="simply-head"><h3 class="fnt-skyblue home_heading">Current Wishes</h3></div>

<div>    
    <section class="row">
        <?php foreach($current as $model){
            $class  =   '';
        echo '<div class="col-md-4 homeWishTpl"><div class="tplColor homeTplBlk">';
        echo '<div><a href="'.Url::to(['wish/view','id'=>$model->w_id]).'"><img src="'.\Yii::$app->homeUrl.'web/'.$model->primary_image.'?v='.strtotime('now').'" class="img-responsive wishImage" alt="Image"></a></div>';
          if($model->likesCount > 0)
              $class    =   'likesView';
          echo  '<div class="smp-wish-desc">';
                echo  '<p><div class="list-icon">
                            <img src="'.$model->wisherPic.'" alt="" />
                            <a href="'.Url::to(['account/profile','id'=>$model->wished_by]).'"><span>'.$model->wisherName.'</span></a>
                        </div></p>
                <p class="desc">'.substr($model->wish_title,0,50).'..</p>
                <p><a class="fnt-green" href="'.Url::to(['wish/view','id'=>$model->w_id]).'">+Read More</a>
                &nbsp;<span data-id="'.$model->w_id.'" class="'.$class.'"> <span id="likecmt_'.$model->w_id.'"  >'.$model->likesCount.'</span> '.($model->likesCount > 1 ? "Loves" : "Love").'</span></p>';

          echo  '</div>';

          echo  '</div></div>';
        }?>
    </section>
</div>
<div class="simply-head pull-right">
    <a href="<?=\Yii::$app->homeUrl?>wish/index"><button class="btn btn-smp-green smpl-brdr" type="button">SEE MORE CURRENT WISHES</button></a>
</div>

<div class="simply-head"><h3 class="fnt-skyblue home_heading">Granted Wishes</h3></div>

<div>    
    <section class="row">
        <?php foreach($models as $model){
            $class  =   '';
        echo '<div class="col-md-4 homeWishTpl"><div class="tplColor homeTplBlk">';
        echo '<div><a href="'.Url::to(['wish/view','id'=>$model->w_id]).'"><img src="'.\Yii::$app->homeUrl.'web/'.$model->primary_image.'?v='.strtotime('now').'" class="img-responsive wishImage" alt="Image" ></a></div>';
          if($model->likesCount > 0)
              $class    =   'likesView';
          echo  '<div class="smp-wish-desc">';
                echo  '<p><div class="list-icon">
                                <img src="'.$model->wisherPic.'" alt="" />
                                <a href="'.Url::to(['account/profile','id'=>$model->wished_by]).'"><span>'.$model->wisherName.'</span></a>
                        </div></p>
                <p class="desc">'.substr($model->wish_title,0,50).'..</p>
                <p><a class="fnt-green" href="'.Url::to(['wish/view','id'=>$model->w_id]).'">+Read More</a>
                &nbsp;<span data-id="'.$model->w_id.'" class="'.$class.'"> <span id="likecmt_'.$model->w_id.'"  >'.$model->likesCount.'</span> '.($model->likesCount > 1 ? "Loves" : "Love").' </span>
                <span><img class="pull-right" src="'.\Yii::$app->homeUrl.'web/images/tick.png" width="30"></span></p>';
                
          echo  '</div>';

          echo  '</div></div>';
        }?>
    </section>
</div>
<div class="simply-head pull-right">
    <a href="<?=\Yii::$app->homeUrl?>wish/granted"><button class="btn btn-smp-green smpl-brdr" type="button">SEE MORE GRANTED WISHES</button></a>
</div>

<div class="simply-head"><h3 class="fnt-skyblue home_heading">Forum</h3></div>

<div>    
    <section class="row">
        <?php foreach($forums as $forum){
            $profile = \app\models\UserProfile::find()->where(['user_id'=>$forum->created_by])->one();
            echo '<div class="col-md-4 homeWishTpl"><div class="tplColor homeTplBlk">';
        
            echo  '<div class="smp-wish-desc">';
            echo  '<h3><a href="'.\Yii::$app->homeUrl.'editorial/editorial-page?id='.$forum->e_id.'&class=article" style="color: #000;">'.$forum->e_title.'</a></h3>
                    <div class="list-icon">
                                <img src="'.\Yii::$app->homeUrl.'web/uploads/users/'.$profile->profile_image.'?v='.strtotime('now').'" alt="" />
                                <a href="'.Url::to(['account/profile','id'=>$forum->created_by]).'"><span>'.$profile->Fullname.'</span></a>
                        </div>                
                    <div class="article_intro">'.substr($forum->e_text,0,200).'..</div>
                <a href="'.\Yii::$app->homeUrl.'editorial/editorial-page?id='.$forum->e_id.'&class=article"><h5>Read More</h5></a>';
                
          echo  '</div>';

          echo  '</div></div>';
        }?>
    </section>
</div>
<div class="simply-head pull-right" style='margin-bottom: 35px;'>
    <a href="<?=\Yii::$app->homeUrl?>editorial/editorial#forum"><button class="btn btn-smp-green smpl-brdr" type="button">SEE MORE ARTICLES & VIDEOS</button></a>
</div>

<div class="modal fade" id="likeModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
      <div class="modal-content" style="width: 80%; margin: auto;">
      <div class="modal-header">
        <a href="#" class="closeModal pull-right">&times;</a>
      </div>
      <div class="modal-body">
          
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    $(".shareIcons").each(function(){
            var elem = $(this);
                    elem.jsSocials({
                    showLabel: false,
                    showCount: true,
                    shares: ["facebook","googleplus", "linkedin",
                    {
                            share: "twitter",           // name of share
                            via: "simply_wishes",       // custom twitter sharing param 'via' (optional)
                            hashtags: "simplywishes,dream_come_true"   // custom twitter sharing param 'hashtags' (optional)
                    }],
                    url : elem.attr("data_url"),
                    text: elem.attr("data_text"),
            });
    });

    $(document).on('click', '.like-wish, .fav-wish', function(){ 
   //$(".like-wish, .fav-wish").on("click",function(){
           var wish_id = $(this).attr("data-w_id");
           var type = $(this).attr("data-a_type");
           var elem = $(this);
           $.ajax({
                   url : '<?=Url::to(['wish/like'])?>',
                   type: 'GET',
                   data: {w_id:wish_id,type:type},
                   success:function(data){
                           if(data == "added"){
                                   if(type=="fav"){
                                           elem.removeClass("txt-smp-orange");
                                           elem.addClass("txt-smp-blue");
                                   }
                                   if(type=="like"){
                                          elem.css('color', '#B23535');
                                           var likecmt = $("#likecmt_"+wish_id).text();
                                           likecmt = parseInt(likecmt) + parseInt(1);
                                           $("#likecmt_"+wish_id).text(likecmt);					
                                   }
                           }
                           if(data == "removed"){
                                   if(type=="fav"){
                                           elem.addClass("txt-smp-orange");
                                           elem.removeClass("txt-smp-blue");
                                   }
                                   if(type=="like"){
                                           elem.css('color', '#fff');
                                           var likecmt = $("#likecmt_"+wish_id).text();
                                           likecmt = parseInt(likecmt) - parseInt(1);
                                           $("#likecmt_"+wish_id).text(likecmt);

                                   }
                           }
                   }
           }); 		
   });

    $(document).ready(function(){	
        var isVisible = false;
        var clickedAway = false;
	$(function(){
		$('.listesinside').popover({   
			html: true,
			content: function () {
				var clone = $($(this).parents(".sharefull-list").find(".shareIcons")).clone(true).removeClass('hide');
				return clone;
			}
		}).click(function(e) {
			//e.preventDefault();
			clickedAway = false;
			isVisible = true;
		});
	});
	/* $(document).on('click','.jssocials-shares',function(){
		 $('.listesinside').popover('hide');
	}); */
	
        $(document).click(function (e) {
            if (isVisible & clickedAway) {  
                $('.listesinside').popover('hide');
                isVisible = clickedAway = false;
            } else {
                clickedAway = true;
            }
        });

        $('body').on('hidden.bs.popover', function (e) {
            $(e.target).data("bs.popover").inState.click = false;
        });
var Wish    =   {
    ajax    :   false
};
        $(document).on('click', '.likesView', function(){
            var val =   $(this).find('span').html();
            if(val <= 0)
                return false;
            
            var wish_id = $(this).data('id');
            if($.trim(wish_id) !== "" )
            {
                if(Wish.ajax)
                    return false;
                
                Wish.ajax   =   true;
                $.ajax({
                    url : '<?=Url::to(['wish/likes-view'])?>',
                    type: 'GET',
                    data: {w_id:wish_id},
                    success:function(data){
                        if(data)
                        {
                            var tpl =   '';
                            var items   =   JSON.parse(data);
                            $.each(items, function(k,v){
                               tpl  +=   '<div class="likeBlock"><a href="<?=\Yii::$app->homeUrl?>account/profile?id='+v.user_id+'"><img src="<?=\Yii::$app->homeUrl?>web/uploads/users/'+v.image+'" width="50px"><span>'+v.name+'</span></a></div>';
                            });
                            
                            $('.modal-body').append(tpl);
                            $('#likeModal').modal({backdrop: 'static', keyboard: false});
                            $('#likeModal').modal('show');
                            
                            $('.closeModal').on('click', function(e){
                                e.preventDefault();
                                $('.modal-body').html('');
                                $('#likeModal').modal('hide');
                            });
                        }
                    },
                    complete: function(){
                        Wish.ajax   =   false;
                    }
                });
            }
        });
    });


/* 
$(document).on("click", ".report-img", function() {
	var wish_id = $(this).attr("data-id");
	 if($.trim(wish_id) !== "" )
	 {
		$.ajax({
			url : '<?=Url::to(['wish/report'])?>',
			type: 'GET',
			data: {w_id:wish_id},
			success:function(data){
				if($.trim(data) == "added")
				{
					alert(" Thanks For your Report. ");
				}
				console.log(data);
			}
		});
	 }
}); */


</script>

web/views/site/success_signup.php
<div style='margin: auto; width: 60%; padding-top: 5%'>
    <p>Thank you <b><?= $profile->firstname ?></b>. Your registration has been submitted.</p>
    <p>
        You will receive an e-mail with instructions on the next step in your Inbox. 
        If you do not receive the e-mail within the next 10 minutes (usually instantly),
        please also check your Spam or Junk box.
    </p>
    <p>The email has been sent to <b><?= $user->email ?></b> </p>
</div>