models/Editorial.php
<?php

namespace app\models;

use app\models\custom\CustomModel;

use Yii;

/**
 * This is the model class for table "editorial".
 *
 * @property integer $e_id
 * @property string $e_title
 * @property string $e_text
 * @property string $e_image
 * @property string $is_video_only
 * @property integer $status
 * @property string $created_at
 */
//toaddreport

class Editorial extends BaseModel // \yii\db\ActiveRecord
{
    public $featured_video_upload;
    public $articleimage;
	public $video;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'editorial';
    }
    



//    //toaddreport
//    public static function find()
//    {
//        $query =new CustomModel(get_called_class());
//         echo $query->createCommand()->getRawSql();
//        return  $query;
//    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['e_title','articleimage'], 'required'],
            [['class'], 'required'],
            //[['e_image'], 'required','except' => 'update_by_editorial_admin'],
            [['e_text','description'], 'string'],
            [['featured_video_url','article_image','description'], 'string'],
            [['status', 'is_video_only'], 'integer'],
            [['created_at'], 'safe'],
            [['e_title'], 'string', 'max' => 250],
            [['e_image','articleimage'], 'file','extensions' => 'jpg,png,jpeg'],
            [['featured_video_upload','video'], 'file','extensions' => 'mp4,mov,wmv', 'maxSize' => 10240000, 'skipOnEmpty' => true],
            /*['featured_video_url', 'required', 'when' => function($model) {
                    return $model->is_video_only == 1;
                }, 'whenClient' => "function (attribute, value) {
                    return $('#video_check').val() == 1;
                }"
            ]*/
        ];
    }

	
    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios['update_by_editorial_admin'] = ['e_title','e_text','e_image','is_video_only','featured_video_url','description']; //Scenario Values Only Accepted
        return $scenarios;
    } 
	
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'e_id' => 'E ID',
            'e_title' => 'Title',
            'e_text' => 'Text',
            'e_image' => 'Image',
            'articleimage'=>'Article Image',
            'status' => 'Status',
            'is_video_only' => 'Is Video Only',
            'created_at' => 'Created At',
            'featured_video_url' => 'Insert the video url in order to upload',
            'featured_video_upload' => 'Upload from your Files',
            'description'=>'Description'
        ];
    }
	
    public function uploadImage(){
        $newFileName = \Yii::$app->security
                ->generateRandomString().'.'.$this->e_image->extension;
        $this->e_image->saveAs('web/uploads/editorial/' . $newFileName,false);
        $this->e_image = 'uploads/editorial/'.$newFileName;
        return true;	
    }

    public function uploadarticleImage(){
        $newFileName = \Yii::$app->security
                ->generateRandomString().'.'.$this->articleimage->extension;
        $this->articleimage->saveAs('web/uploads/editorial/' . $newFileName,false);
        $this->article_image = 'uploads/editorial/'.$newFileName;
        return true;
    }
    public function isLiked($byUser){
            if(EditorialActivity::find()->where(['e_id'=>$this->e_id,'activity'=>'like','user_id'=>$byUser])->one()!= null)
                    return true;
            else return false;
    }
    
    public function getLikes()
    {
        return $this->hasMany(EditorialActivity::className(), ['e_id'=>'e_id'])->andOnCondition(['activity' => 'like']);
    }
    
    public function getLikesCount()
    {
        return EditorialActivity::find()->where(['e_id'=>$this->e_id,'activity'=>'like'])->count();
    }

    public function getAuthor()
    {
        return $this->hasOne(UserProfile::className(), ['user_id' => 'created_by']);
    }
    public function getlikeByUser()
    {
        return $this->hasMany(EditorialActivity::className(), ['e_id'=>'e_id'])->andOnCondition(['activity' => 'like']);
    }
    
}

controllers/HappyStoriesController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\UploadedFile;
use app\models\HappyStories;
use app\models\StoryActivity;
use app\models\ReportContent;
use app\models\User;
use app\models\UserProfile;
use app\models\search\SearchHappyStories;
use app\models\search\SearchReportContent;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Url;
use app\models\HappyStoriesComments;
use app\models\HappyStoriesCommentActivity;

class HappyStoriesController extends \yii\web\Controller
{
	 /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(), 
                'except' => ['index','story-details','scroll-happy','likes-view'],	
                'rules' => [
                    [
                        'actions' => ['create','update','my-story','delete','permission','view','update-new',
                            'scroll-my-happy','like','happy-stories-comments','update-comment','delete-comment',
                            'commentreply','comment-likes-view','like-comment','report-story','content-management'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }
	
    public function actionIndex()
    {		
        /* $stories = HappyStories::find()->where(['status'=>0])->orderBy('hs_id Desc')->all();				
        return $this->render('index', ['stories' => $stories]); */
				
        $searchModel = new SearchHappyStories();
        $dataProvider = $searchModel->searchLive(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);	
    }

    
    public function actionReportStory(){

        $report = new ReportContent();
        $postData = Yii::$app->request->post();
        // print_r($postData);exit;
        $report->content_id = $postData['hs_id'];
        $report->report_user = \Yii::$app->user->id;
        $report->reported_user = $postData['reported_user'];
        $report->report_type="happy_stories";
        $report->date = date('Y-m-d H:i:s'); 

        if ($report->save()){
            Utils::sendEmail(1,'',21);
            return true;
        } 
        return false;
    }
        	
	 public function actionContentManagement()
     {		
     
         $searchModel = new SearchReportContent();
         $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
         return $this->render('content-management', [
             'searchModel' => $searchModel,
             'dataProvider' => $dataProvider,
         ]);
         
     }
	

    public function actionScrollHappy($page)
    {
        $searchModel = new SearchHappyStories();
        $dataProvider = $searchModel->searchLive(Yii::$app->request->queryParams);
	$dataProvider->pagination->page = $page;
        $str = '';
        foreach($dataProvider->models as $story){
            $str .= $story->happyAsCard;
        }
        return $str;
    }
	
	
	 public function actionMyStory()
    {			
		$user = User::findOne(\Yii::$app->user->id);
		$profile = UserProfile::find()->where(['user_id'=>\Yii::$app->user->id])->one();
	
		$searchModel = new SearchHappyStories();
        $dataProvider = $searchModel->searchMystories(Yii::$app->request->queryParams);
		
        return $this->render('my-story', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
			'user' => $user,
			'profile' => $profile
        ]);
		
    }
    
    public function actionLikesView($w_id)
    {
        $story = $this->findModel($w_id);
        $likedUser  =   [];
        if( ! empty($story->likes))
        {
            foreach($story->likes as $key => $like)
            {
                $profile = UserProfile::find()->where(['user_id'=>$like->user_id])->one();
                
                $likedUser[$key]['user_id'] =   $profile->user_id;
                $likedUser[$key]['name'] =   $profile->firstname.' '.$profile->lastname;
                $likedUser[$key]['image'] =   $profile->profile_image;
            }
        }
        
        return json_encode($likedUser);
    }
	
	
    public function actionScrollMyHappy($page)
    {
        $searchModel = new SearchHappyStories();
        $dataProvider = $searchModel->searchMystories(Yii::$app->request->queryParams);
		$dataProvider->pagination->page = $page;
        $str = '';
        foreach($dataProvider->models as $story){
			$str .= $story->myHappyAsCard;
        }
        return $str;
    }
	
    public function actionCreate()
    {
        $model = new HappyStories();
        $user = User::findOne(\Yii::$app->user->id);
        $profile = UserProfile::find()->where(['user_id'=>\Yii::$app->user->id])->one();
		
		  
        if ($model->load(Yii::$app->request->post())) {
            
            $model->user_id = \Yii::$app->user->id;
            $model->story_image = UploadedFile::getInstance($model, 'story_image');
            
            if(!empty($model->story_image)) {
                    if(!$model->uploadImage())
                            return;
            }else 
            {
                    $model->story_image = $model->dulpicate_image;
            }

            if($model->save())
            {
                Yii::$app->session->setFlash('success_adminhappystory');
                $model->sendSuccessEmail(\Yii::$app->user->id);
                return $this->redirect(['my-story']);
            }	
            else
            {					
                return $this->render('create', ['model' => $model,'user' => $user,'profile' => $profile]);
            }	
				
        } else {
            return $this->render('create', [
                'model' => $model,
                'user' => $user,
                'profile' => $profile
            ]);
        }
    }
	
    public function actionStoryDetails($id)
    {		
        $model = HappyStories::findOne($id);	
        
        if( ! $model)
            return $this->goHome();
        
        $listcomments = new HappyStoriesComments();
        $comments = $listcomments->find()->where(['hs_id'=>$id,'parent_id'=>0, 'status'=>0])->orderBy('hs_comment_id Desc')->all();		 
        
        return $this->render('story_full', [
            'model' =>$model,'comments'=>$comments,'listcomments'=>$listcomments
        ]); 
        
        return $this->render('story_full', ['model' => $model]);
    }
	
    public function actionUpdate($id)
    {
        $model = HappyStories::findOne($id);
        $current_image = $model->story_image;
        //$model->scenario = 'update_by_happystory_user';

        $user = User::findOne(\Yii::$app->user->id);
        $profile = UserProfile::find()->where(['user_id'=>\Yii::$app->user->id])->one();
		
        if ($model->load(Yii::$app->request->post())){
			
        /**		Image Uploaded for Update function Line 
        **/		
        $model->story_image = UploadedFile::getInstance($model, 'story_image');										
        if(!empty($model->story_image)){ 
                if(!$model->uploadImage())
                        return;
        }
         else
        {					
                if(!empty($model->dulpicate_image) && ($model->dulpicate_image != $current_image ))
                {
                        $model->story_image = $model->dulpicate_image;
                } else {
                        $model->story_image = $current_image;
                }					
        }

        if($model->save())
        {	Yii::$app->session->setFlash('success_happystory');
                //return $this->redirect(['story-details', 'id' => $model->hs_id]);
                return $this->redirect(['my-story']);
        } else {

                return $this->render('update', ['model' => $model,'user' => $user,
        'profile' => $profile,]);
        }
        } else {
            return $this->render('update', [
                'model' => $model,
				'user' => $user,
				'profile' => $profile,
            ]);
        }
    }
	
	/**
	 * Like a story
	 * User has to be logged in to like a wish
	 * Param: wish id
	 * @return boolean
	 */
	public function actionLike($s_id,$type)
	{
		if(\Yii::$app->user->isGuest)
			return $this->redirect(['site/login','red_url'=>Yii::$app->request->referrer]);
		$story = $this->findModel($s_id);
		$activity = StoryActivity::find()->where(['story_id'=>$story->hs_id,'activity'=>$type,'user_id'=>\Yii::$app->user->id])->one();
		if($activity != null){
			$activity->delete();
			return "removed";
		}
			$activity = new StoryActivity();
		$activity->story_id = $story->hs_id;
		$activity->activity = $type;
		$activity->user_id = \Yii::$app->user->id;
		if($activity->save())
			return "added";
		else return false;
	}
	
    /**
     * Finds the story model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Wish the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = HappyStories::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
	
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['happy-stories/my-story']);  
    }
	
	 public function actionPermission()
    {		
		/* $stories = HappyStories::find()->orderBy('hs_id Desc')->all();				
        return $this->render('index', ['stories' => $stories]); */
	
		$searchModel = new SearchHappyStories();

views/happy-stories/content-management.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

use app\models\HappyStoriesComments;
use app\models\WishComments;
use app\models\DonationComments;
use app\models\Donation;
use app\models\Wish;
use app\models\EditorialComments;


/* @var $this yii\web\View */
/* @var $searchModel app\models\search\SearchEditorial */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Content Management';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="editorial-index">

    <h3 class="fnt-skyblue" ><?= Html::encode($this->title) ?></h3>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
		
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

			[
				'attribute' => 'fullname',
				'label' => 'Report user',
				'value' => 'reportUser.fullname',	
				'enableSorting' => true,					
			],	
			
			[
				'attribute' => 'reported_user',
				'label' => 'Reported user',
				'value' => 'reportedUser.fullname',
				'enableSorting' => true,					
			],	    				
			[
				'attribute' => 'comment',
				'label' => 'Comment',
				'value' => 'comment',
				'enableSorting' => false,		
			],	 
			[
                'attribute'=>'report_type',
				'value' => 'report_type',
                'filter'=>Html::activeDropDownList($searchModel, 'report_type', array("wish"=>"wish","user"=>"user","comment"=>"comment","message"=>"message","wish_comment"=>"wish_comment","article_comment"=>"article_comment","article"=>"article","donation"=>"donation"),['class'=>'form-control','prompt' => '--Select type--']),
				'enableSorting' => true,
            ],
			
			[
                'attribute'=>'blocked',
				'value' => function($model, $key, $index)
				{   
						if($model->blocked == '0')
						{
							return 'Not Blocked';
						}
						else
						{   
							return 'Blocked';
						}
				},
                'filter'=>Html::activeDropDownList($searchModel, 'blocked', array("0"=>"Not blocked","1"=>"Blocked"),['class'=>'form-control','prompt' => '--Select Status--']),
				'enableSorting' => false,
            ],
	
			[
  'class' => 'yii\grid\ActionColumn',
  'template' => '{view}{remove}{delete}',
  'buttons' => [
    'view' => function ($url, $model) {
		$url="";
		switch ($model->report_type){
			case 'wish':
				$url = Url::to(['wish/view','id'=>$model->content_id]);
				break;
			case 'donation':
				$url = Url::to(['donation/view','id'=>$model->content_id]);
				break;				
			case 'donation_comment':
				$donation = DonationComments::find()->where(['d_comment_id'=>$model->content_id])->one();
				$url = Url::to(['/donation/view','id'=>$donation->d_id]);
				break;				
			case 'wish_comment':
				$wish = WishComments::find()->where(['w_comment_id'=>$model->content_id])->one();
				if (isset($wish->w_id)){
                    $url = Url::to(['/wish/view','id'=>$wish->w_id]);
                }
				break;				
			case 'user':
				$url = Url::to(['account/profile','id'=>$model->reported_user]);
				break;
			// case 'message':
			// 	$url = Url::to(['account/inbox-user-message','id'=>$model->report_user]);
			// 	break;				
			case 'editorial':
				$url = Url::to(['/editorial/editorial-page','id'=>$model->content_id, 'class'=>'article']);
				break;	
			case 'editorial_comment':
				$editorial = EditorialComments::find()->where(['e_comment_id'=>$model->content_id])->one();
				$url = Url::to(['/editorial/editorial-page','id'=>$editorial->e_id]);
				break;					
			case 'happy_stories':
				$url = Url::to(['/happy-stories/story-details','id'=>$model->content_id]);
				break;	
			case 'happy_stories_comment':
				$hs = HappyStoriesComments::find()->where(['hs_comment_id'=>$model->content_id])->one();
				$url = Url::to(['/happy-stories/story-details','id'=>$hs->hs_id]);
				break;					
			default :
				$url=""	;
				break;
		}
		
        return Html::a('<span style="margin-left:5px" class="glyphicon glyphicon-eye-open"></span>', $url, [
			'class' => 'viewcheck',	
			'id'=>$model->content_id, 	
			'type'=>$model->report_type, 	
			'title' => Yii::t('app', 'View content'),
        ]);
    },
	  'remove' => function ($url, $model) {
		  return Html::a('<span style="margin-left:5px" class="glyphicon glyphicon-trash"></span>', '/content-management/remove?id='.$model->id, [
			  'class' => 'removecheck',
			  'title' => Yii::t('app', 'Delete content'),
		  ]);
	  },
	// 'block' => function ($url, $model) {
    //     return Html::a('<span style="margin-left:5px" class="glyphicon glyphicon-ban-circle"></span>', '/content-management/block?id='.$model->id, [
    //                 'title' => Yii::t('app', 'Block content'),
    //     ]);
    // },
	'delete' => function ($url, $model) {
         return Html::a('<span style="margin-left:5px" class="glyphicon glyphicon-minus-sign"></span>', '#', [
					'class' => 'deletecheck',
					'for'=>$model->id, 
                    'title' => Yii::t('app', 'Delete from reports (takes no action regarding content)'),					
        ]); 
		
    },
  ],
],


        ],
    ]); ?>
</div>

<script>

$(document).on('click', '.removecheck', function(){ 
	var checkmsg = confirm("Are you sure you want to delete this item?");	
	if(checkmsg == false)
	{
		return false;
	}
});

$(document).on('click', '.deletecheck', function(){ 
		var checkmsg = confirm("Are you sure you want to delete this item?");	
		if(checkmsg == false)
		{
			return false;
		}
		
		var id = $(this).attr('for');
		$.ajax({
			url : '<?=Url::to(['content-management/delete'])?>',
			type: 'POST',
			data: { id:id },
			success:function(data){
				console.log(data);
				// location.reload();
			}
		});
		
	}); 

	
</script>

views/happy-stories/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use app\models\UserProfile;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model app\models\Editorial */

$this->title = 'Happy Stories';
$this->params['breadcrumbs'][] = ['label' => 'Editorials', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="editorial-create smp-mg-bottom">
        <?php $detect = new Mobile_Detect; ?>
        <?php if (!$detect->isMobile() && !$detect->isTablet()) { ?>
        <div class="row tell-ur-story">
            <div class="col-sm-6"><h3 class="fnt-skyblue">Happy Stories</h3></div>
            <div class="col-sm-6">
                <div class="pull-right newtest" style="margin-bottom : -30px;">
                    <a class='btn btn-success' href="<?=Yii::$app->homeUrl?>happy-stories/create">Tell Your Happy Story</a>
                    <?php echo $this->render('_search', ['model' => $searchModel]); ?>
                </div>
            </div>
        </div>
        <h4 class='smp_about_slide'>Stories written by our users' whose wishes have been granted.</h4>
        <?php }else{?>
        <div class="row tell-ur-story">
            <div class="col-sm-4"><h3 class="fnt-skyblue"  style="text-align: center;">Happy Stories</h3></div>
            <br>
            <div class="newtest" style="text-align: center !important;">
                <h4 class='smp_about_slide'>Stories written by our users' whose wishes have been granted.</h4>
            </div>
            <div class="col-sm-4" style="padding-bottom: 50px;">
                <div class="pull-left" style="height: 45px;">
                    <a class='btn btn-success' href="<?=Yii::$app->homeUrl?>happy-stories/create">Tell Your Happy Story</a>
                </div>
            </div>
            <div class="col-sm-4" style="margin-right: 50px;">
                <div class="pull-left">
                    <?php echo $this->render('_search', ['model' => $searchModel]); ?>
                </div>
            </div>
        </div>
        <?php } ?>
    <?php Pjax::begin() ?>
    <div id="gridheight">
	<?php
	
	if(!empty($dataProvider->models))
	{
            foreach($dataProvider->models as $story)
            {
                $class  =   '';	
                $wish_details = $story->wish;
                
                if($story->likesCount > 0)
                    $class    =   'likesView';
                else
                    $class     =    'hide';
                
		      $profile = UserProfile::find()->where(['user_id'=>$story->user_id])->one();
                if(!empty($wish_details)) {
                    ?>
                    <div class="happystory smp-mg-bottom">
                        <div class="media">
                            <div class="media-left sharefull-list">
                                <img alt="story" src="<?= Yii::$app->homeUrl ?>web/<?= $story->story_image; ?>"
                                     class="media-object" style="width: 200px;border: solid 2px #000;">
                                <p>
                                    <span data-id="<?= $story->hs_id ?>" class="likesBlk <?php echo $class ?>">
                                        <span id="likecmt_<?= $story->hs_id ?>"> <?= $story->likesCount ?>  </span>
                                        <?php echo $story->likesCount > 1 ? 'Loves' : 'Love'; ?>
                                    </span> &nbsp;
                                    <?php

                                    if (!$story->isLiked(\Yii::$app->user->id))
                                        echo '<span title="Love it" data-w_id="' . $story->hs_id . '" data-a_type="like" class="like-wish glyphicon glyphicon-heart txt-smp-pink"></span>';
                                    else
                                        echo '<span title="You loved it" data-w_id="' . $story->hs_id . '" data-a_type="like" class="like-wish glyphicon glyphicon-heart txt-smp-pink" style="color:#B23535;"></span>';
                                    ?>
                                    <!--<i class="fa fa-save txt-smp-orange"></i> &nbsp;
                                    <i class="fa fa-thumbs-o-up txt-smp-green"></i>-->

                                    <span title="Share it" data-placement="top" data-popover-content=""><img
                                            data-placement="top" class="listesinside"
                                            src="<?= Yii::$app->homeUrl ?>web/images/Share-Icon.png"/></span>
                                <div class="shareIcons hide"
                                     data_text="<?php echo (isset($wish_details->wish_title)) ? $wish_details->wish_title : ''; ?>"
                                     data_url="<?= Url::to(['happy-stories/story-details', 'id' => $story->hs_id], true) ?>"></div>
                                </p>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading"><?php echo (isset($wish_details->wish_title)) ? $wish_details->wish_title : ''; ?></h4>
                                <a href="<?= Url::to(["account/profile", "id" => $story->user_id]) ?>">By: <?= $story->author->fullname; ?></a>
                                <p> <?= substr($story->story_text, 0, 450) ?></p>
                                <a href="<?= Yii::$app->homeUrl ?>happy-stories/story-details?id=<?= $story->hs_id; ?>">
                                    <h5>Read More</h5></a>
                            </div>
                        </div>
                    </div>
                    <?php
                }
            }
            } else {
                echo "<div style='text-align: center;margin: 30px;'>Sorry, no Happy Stories found!</div>";
            }?>
    </div>
    <div>
        <?php
        echo \yii\widgets\LinkPager::widget([
            'pagination'=>$dataProvider->pagination,
        ]);?> 
    </div>
    <?php Pjax::end() ?>
</div>	
<div class="modal fade" id="likeModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
      <div class="modal-content" style="width: 80%; margin: auto;">
      <div class="modal-header">
        <a href="#" class="closeModal pull-right">&times;</a>
      </div>
      <div class="modal-body">
          
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">

$(document).ready(function(){
    $(".shareIcons").each(function(){
		var elem = $(this);
		elem.jsSocials({
                    showLabel: false,
                    showCount: true,
                    shares: ["facebook",{
                        share: "pinterest",           // name of share
                        via: "simplywishes5244",
                        media:elem.attr("data_image"),// custom twitter sharing param 'via' (optional)
                        hashtags: "SimplyWishes,Wish,Dream,Connect"    // custom twitter sharing param 'hashtags' (optional)
                    },
                    {
                            share: "twitter",           // name of share
                            via: "simply_wishes",       // custom twitter sharing param 'via' (optional)
                            hashtags: "SimplyWishes,Wish,Dream,Connect"    // custom twitter sharing param 'hashtags' (optional)
                    }],
                    url : elem.attr("data_url"),
                    text: elem.attr("data_text")
		});
	});
        
var Wish    =   {
    ajax    :   false
};
$(document).on('click', '.likesView', function(){
            var val =   $(this).find('span').html();
            if(val <= 0)
                return false;
            
            var wish_id = $(this).data('id');
            if($.trim(wish_id) !== "" )
            {
                if(Wish.ajax)
                    return false;
                
                Wish.ajax   =   true;
                
                $.ajax({
                    url : '<?=Url::to(['happy-stories/likes-view'])?>',
                    type: 'GET',
                    data: {w_id:wish_id},
                    success:function(data){
                        if(data)
                        {
                            var tpl =   '';
                            var items   =   JSON.parse(data);
                            $.each(items, function(k,v){
                               tpl  +=   '<div class="likeBlock"><a href="<?=\Yii::$app->homeUrl?>account/profile?id='+v.user_id+'"><img src="<?=\Yii::$app->homeUrl?>web/uploads/users/'+v.image+'" width="50px"><span>'+v.name+'</span></a></div>';
                            });
                            
                            $('.modal-body').append(tpl);
                            $('#likeModal').modal({backdrop: 'static', keyboard: false});
                            $('#likeModal').modal('show');
                            
                            $('.closeModal').on('click', function(e){
                                e.preventDefault();
                                $('.modal-body').html('');
                                $('#likeModal').modal('hide');
                            });
                        }
                    },
                    complete: function(){
                        Wish.ajax   =   false;
                    }
                });
            }
        });
        
        $(document).on('click', '.like-wish', function(){ 
		var s_id = $(this).attr("data-w_id");
		var type = $(this).attr("data-a_type");
		var elem = $(this);
		$.ajax({
			url : '<?=Url::to(['happy-stories/like'])?>',
			type: 'GET',
			data: {s_id:s_id,type:type},
			success:function(data){
				if(data == "added"){
					if(type=="fav"){
						elem.removeClass("txt-smp-orange");
						elem.addClass("txt-smp-blue");
					}
					if(type=="like"){
						elem.css('color', '#B23535');
						var likecmt = $("#likecmt_"+s_id).text();
						likecmt = parseInt(likecmt) + parseInt(1);
						$("#likecmt_"+s_id).text(likecmt);
                                                $("#likecmt_"+s_id).parent('.likesBlk').removeClass('hide');
					}
				}
				if(data == "removed"){
					if(type=="fav"){
						elem.addClass("txt-smp-orange");
						elem.removeClass("txt-smp-blue");
					}
					if(type=="like"){
						elem.css('color', '#fff');
						var likecmt = $("#likecmt_"+s_id).text();
						likecmt = parseInt(likecmt) - parseInt(1);
						$("#likecmt_"+s_id).text(likecmt);
                                                if(likecmt == 0)
                                                    $("#likecmt_"+s_id).parent('.likesBlk').addClass('hide');
					}
				}
			}
		});
	});
        });
    var isVisible = false;
var clickedAway = false;
$(document).on("click", ".listesinside", function() {
    $(function(){
        $('.listesinside').popover({   
            html: true,
            content: function () {
                var clone = $($(this).parents(".sharefull-list").find(".shareIcons")).clone(true).removeClass('hide');
                return clone;
            }
        }).click(function(e) {
            e.preventDefault();
            clickedAway = false;
            isVisible = true;
        });
    });
 
});

$(document).click(function (e) {
    if (isVisible & clickedAway) {
        $('.listesinside').popover('hide');
        isVisible = clickedAway = false;
    } else {
        clickedAway = true;
    }
});

$('body').on('hidden.bs.popover', function (e) {
    $(e.target).data("bs.popover").inState.click = false;
});
	
</script>