web/controllers/HappyStoriesController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\UploadedFile;
use app\models\HappyStories;
use app\models\StoryActivity;
use app\models\User;
use app\models\UserProfile;
use app\models\search\SearchHappyStories;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Url;

class HappyStoriesController extends \yii\web\Controller
{
	 /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(), 
                'except' => ['index','story-details','scroll-happy','likes-view'],	
                'rules' => [
                    [
                        'actions' => ['create','update','my-story','delete','permission','view','update-new','scroll-my-happy','like'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }
	
    public function actionIndex()
    {		
        /* $stories = HappyStories::find()->where(['status'=>0])->orderBy('hs_id Desc')->all();				
        return $this->render('index', ['stories' => $stories]); */
				
        $searchModel = new SearchHappyStories();
        $dataProvider = $searchModel->searchLive(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);	
    }

    public function actionScrollHappy($page)
    {
        $searchModel = new SearchHappyStories();
        $dataProvider = $searchModel->searchLive(Yii::$app->request->queryParams);
	$dataProvider->pagination->page = $page;
        $str = '';
        foreach($dataProvider->models as $story){
            $str .= $story->happyAsCard;
        }
        return $str;
    }
	
	
	 public function actionMyStory()
    {			
		$user = User::findOne(\Yii::$app->user->id);
		$profile = UserProfile::find()->where(['user_id'=>\Yii::$app->user->id])->one();
	
		$searchModel = new SearchHappyStories();
        $dataProvider = $searchModel->searchMystories(Yii::$app->request->queryParams);
		
        return $this->render('my-story', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
			'user' => $user,
			'profile' => $profile
        ]);
		
    }
    
    public function actionLikesView($w_id)
    {
        $story = $this->findModel($w_id);
        $likedUser  =   [];
        if( ! empty($story->likes))
        {
            foreach($story->likes as $key => $like)
            {
                $profile = UserProfile::find()->where(['user_id'=>$like->user_id])->one();
                
                $likedUser[$key]['user_id'] =   $profile->user_id;
                $likedUser[$key]['name'] =   $profile->firstname.' '.$profile->lastname;
                $likedUser[$key]['image'] =   $profile->profile_image;
            }
        }
        
        return json_encode($likedUser);
    }
	
	
    public function actionScrollMyHappy($page)
    {
        $searchModel = new SearchHappyStories();
        $dataProvider = $searchModel->searchMystories(Yii::$app->request->queryParams);
		$dataProvider->pagination->page = $page;
        $str = '';
        foreach($dataProvider->models as $story){
			$str .= $story->myHappyAsCard;
        }
        return $str;
    }
	
    public function actionCreate()
    {
        $model = new HappyStories();
        $user = User::findOne(\Yii::$app->user->id);
        $profile = UserProfile::find()->where(['user_id'=>\Yii::$app->user->id])->one();
		
		  
        if ($model->load(Yii::$app->request->post())) {
            
            $model->user_id = \Yii::$app->user->id;
            $model->story_image = UploadedFile::getInstance($model, 'story_image');
            
            if(!empty($model->story_image)) {
                    if(!$model->uploadImage())
                            return;
            }else 
            {
                    $model->story_image = $model->dulpicate_image;
            }

            if($model->save())
            {
                Yii::$app->session->setFlash('success_adminhappystory');
                $model->sendSuccessEmail(\Yii::$app->user->id);
                return $this->redirect(['my-story']);
            }	
            else
            {					
                return $this->render('create', ['model' => $model,'user' => $user,'profile' => $profile]);
            }	
				
        } else {
            return $this->render('create', [
                'model' => $model,
                'user' => $user,
                'profile' => $profile
            ]);
        }
    }
	
    public function actionStoryDetails($id)
    {		
		$model = HappyStories::findOne($id);		
        return $this->render('story_full', ['model' => $model]);
	
    }
	
    public function actionUpdate($id)
    {
        $model = HappyStories::findOne($id);
        $current_image = $model->story_image;
        //$model->scenario = 'update_by_happystory_user';

        $user = User::findOne(\Yii::$app->user->id);
        $profile = UserProfile::find()->where(['user_id'=>\Yii::$app->user->id])->one();
		
        if ($model->load(Yii::$app->request->post())){
			
        /**		Image Uploaded for Update function Line 
        **/		
        $model->story_image = UploadedFile::getInstance($model, 'story_image');										
        if(!empty($model->story_image)){ 
                if(!$model->uploadImage())
                        return;
        }
         else
        {					
                if(!empty($model->dulpicate_image) && ($model->dulpicate_image != $current_image ))
                {
                        $model->story_image = $model->dulpicate_image;
                } else {
                        $model->story_image = $current_image;
                }					
        }

        if($model->save())
        {	Yii::$app->session->setFlash('success_happystory');
                //return $this->redirect(['story-details', 'id' => $model->hs_id]);
                return $this->redirect(['my-story']);
        } else {

                return $this->render('update', ['model' => $model,'user' => $user,
        'profile' => $profile,]);
        }
        } else {
            return $this->render('update', [
                'model' => $model,
				'user' => $user,
				'profile' => $profile,
            ]);
        }
    }
	
	/**
	 * Like a story
	 * User has to be logged in to like a wish
	 * Param: wish id
	 * @return boolean
	 */
	public function actionLike($s_id,$type)
	{
		if(\Yii::$app->user->isGuest)
			return $this->redirect(['site/login','red_url'=>Yii::$app->request->referrer]);
		$story = $this->findModel($s_id);
		$activity = StoryActivity::find()->where(['story_id'=>$story->hs_id,'activity'=>$type,'user_id'=>\Yii::$app->user->id])->one();
		if($activity != null){
			$activity->delete();
			return "removed";
		}
			$activity = new StoryActivity();
		$activity->story_id = $story->hs_id;
		$activity->activity = $type;
		$activity->user_id = \Yii::$app->user->id;
		if($activity->save())
			return "added";
		else return false;
	}
	
    /**
     * Finds the story model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Wish the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = HappyStories::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
	
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['happy-stories/my-story']);  
    }
	
	 public function actionPermission()
    {		
		/* $stories = HappyStories::find()->orderBy('hs_id Desc')->all();				
        return $this->render('index', ['stories' => $stories]); */
	
		$searchModel = new SearchHappyStories();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		
        return $this->render('index_new', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
		
    }
	
	
	 /**
     * Displays a single Editorial model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
	
	
	public function actionUpdateNew($id)
    {
        $model = HappyStories::findOne($id);
		$model->scenario = 'update_by_happystory_adminuser';
		
        if ($model->load(Yii::$app->request->post())){
		
				if($model->save())
				{	
					$model->sendAdminSuccessEmail( $model->user_id);
					return $this->redirect(['view', 'id' => $model->hs_id]);
				} else {
			
				return $this->render('update_new', ['model' => $model]);
			}
			
			
        } else {
            return $this->render('update_new', ['model' => $model]);
        }
    }
	
}

web/views/happy-stories/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use app\models\UserProfile;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model app\models\Editorial */

$this->title = 'Happy Stories';
$this->params['breadcrumbs'][] = ['label' => 'Editorials', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="editorial-create smp-mg-bottom">
    <div class="row tell-ur-story">
        <div class="col-sm-6"><h3 class="fnt-skyblue">Happy Stories</h3></div>
        <div class="col-sm-6">
            <div class="pull-right newtest" style="margin-bottom : -30px;">
                <a class='btn btn-success' href="<?=Yii::$app->homeUrl?>happy-stories/create">Tell Your Happy Story</a> 
                <?php echo $this->render('_search', ['model' => $searchModel]); ?>
            </div>
        </div>
    </div>
    <h4 class='smp_about_slide'>Stories written by our user's whose wishes have been granted.</h4>
    <?php Pjax::begin() ?>
    <div id="gridheight">
	<?php
	
	if(!empty($dataProvider->models))
	{
            foreach($dataProvider->models as $story)
            {
                $class  =   '';	
                    
                if($story->likesCount > 0)
                    $class    =   'likesView';
		$profile = UserProfile::find()->where(['user_id'=>$story->user_id])->one();?>
                    <div class="happystory smp-mg-bottom">
                        <div class="media"> 
                            <div class="media-left"> 
                                <img alt="story" src="<?=Yii::$app->homeUrl?>web/<?= $story->story_image; ?>" class="media-object"   style="width: 200px;border: solid 2px #000;">
                                <span data-id="<?= $story->hs_id?>" class="<?php echo $class ?>"> <?=$story->likesCount?>  <?php echo $story->likesCount > 1 ? 'Loves' : 'Love'; ?></span>
                            </div> 
                            <div class="media-body"> 
                                <h4 class="media-heading"><?= $story->story_title; ?></h4>
                                <a href="<?= Url::to(["account/profile","id"=>$story->user_id]) ?>">Author: <?= $story->author->fullname; ?></a>
                                <p> <?=substr($story->story_text,0,450)?></p>
                                <a href="<?=Yii::$app->homeUrl?>happy-stories/story-details?id=<?= $story->hs_id; ?>" ><h5>Read More</h5></a>
                            </div> 
                        </div>
                    </div>
            <?php
            }
            } else {
                echo "sorry, no Happy Stories yet!";
            }?>
    </div>
    <div>
        <?php
        echo \yii\widgets\LinkPager::widget([
            'pagination'=>$dataProvider->pagination,
        ]);?> 
    </div>
    <?php Pjax::end() ?>
</div>	
<div class="modal fade" id="likeModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
      <div class="modal-content" style="width: 80%; margin: auto;">
      <div class="modal-header">
        <a href="#" class="closeModal pull-right">&times;</a>
      </div>
      <div class="modal-body">
          
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
var Wish    =   {
    ajax    :   false
};
$(document).on('click', '.likesView', function(){
            var val =   $(this).find('span').html();
            if(val <= 0)
                return false;
            
            var wish_id = $(this).data('id');
            if($.trim(wish_id) !== "" )
            {
                if(Wish.ajax)
                    return false;
                
                Wish.ajax   =   true;
                
                $.ajax({
                    url : '<?=Url::to(['happy-stories/likes-view'])?>',
                    type: 'GET',
                    data: {w_id:wish_id},
                    success:function(data){
                        if(data)
                        {
                            var tpl =   '';
                            var items   =   JSON.parse(data);
                            $.each(items, function(k,v){
                               tpl  +=   '<div class="likeBlock"><a href="<?=\Yii::$app->homeUrl?>account/profile?id='+v.user_id+'"><img src="<?=\Yii::$app->homeUrl?>web/uploads/users/'+v.image+'" width="50px"><span>'+v.name+'</span></a></div>';
                            });
                            
                            $('.modal-body').append(tpl);
                            $('#likeModal').modal({backdrop: 'static', keyboard: false});
                            $('#likeModal').modal('show');
                            
                            $('.closeModal').on('click', function(e){
                                e.preventDefault();
                                $('.modal-body').html('');
                                $('#likeModal').modal('hide');
                            });
                        }
                    },
                    complete: function(){
                        Wish.ajax   =   false;
                    }
                });
            }
        });
	
</script>

web/views/happy-stories/my-story.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;
use app\models\UserProfile;

/* @var $this yii\web\View */
/* @var $model app\models\Editorial */

$this->title = 'Happy Wish Stories';
$this->params['breadcrumbs'][] = ['label' => 'Editorials', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<?php echo $this->render('@app/views/account/_profilenew',['user'=>$user,'profile'=>$profile])?>

<div class="col-md-8" id="scroll-evt">
        <div class="row tell-ur-story">
            <div class="col-sm-6"><h3 class="fnt-skyblue">My Happy Stories</h3></div>
            <div class="col-sm-6">
                <div class="pull-right">
                    <a class='btn btn-success' href="<?=Yii::$app->homeUrl?>happy-stories/create">Tell Your Happy Story</a>
                </div>
            </div>
        </div>
	
	<?php if (Yii::$app->session->hasFlash('success_happystory')): ?>
            <div class="alert alert-success" style="margin-top: 20px;  width: 80%;">
                    Your Story has been Updated Successfully.	
            </div>
	<?php endif; ?>	
	<?php if (Yii::$app->session->hasFlash('success_adminhappystory')): ?>
            <div class="alert alert-success" style="margin-top: 20px;  width: 80%;">
                    Your Story has been Created and is waiting for Site Approval.
            </div>
	<?php endif; ?>	
        <?php Pjax::begin() ?>
	<div class="grid" data-masonry='{ "itemSelector": ".grid-item" }'>
		
		<?php
		
        if(isset($dataProvider->models) && !empty($dataProvider->models))
        {		
            foreach($dataProvider->models as $story)
            {
                $class  =   '';
                $profile = UserProfile::find()->where(['user_id'=>$story->user_id])->one();	

                if($story->likesCount > 0)
                    $class    =   'likesView';
                ?>
				
                <div class="col-md-12 happystory smp-mg-bottom">
                    <div class="media"> 
                        <div class="media-left"> 
                                <img alt="story" src="<?=Yii::$app->homeUrl?>web/<?= $story->story_image; ?>" class="media-object"   style="width: 200px;border: solid 2px #000;">
                                <span data-id="<?= $story->hs_id?>" class="<?php echo $class ?>">  <?=$story->likesCount?>  <?php echo $story->likesCount > 1 ? 'Loves' : 'Love'; ?> </span>
                        </div> 
                        <div class="media-body">
                            <h4 class="media-heading"><?php echo $story->story_title; ?></h4>

                            <a href="<?= Url::to(["account/profile","id"=>$story->user_id]) ?>">Author: <?= $story->author->fullname; ?></a>
                            <p> <?=substr($story->story_text,0,450)?></p>
                            <a href="<?=Yii::$app->homeUrl?>happy-stories/story-details?id=<?= $story->hs_id; ?>" ><h5>Read More</h5></a>
                            <?php if(\Yii::$app->user->id == $story->user_id){ ?>
                                <div>
                                        <?= Html::a('<i class="glyphicon glyphicon-pencil" aria-hidden="true"></i> Update', ['update', 'id' => $story->hs_id], ['class' => 'btn btn-warning']) ?>


                                </div> 
                            <?php } ?>
                        </div> 
                    </div>
                </div>

            <?php
            }
        } else {
                echo "Write any interesting story about your wishes that has been granted.";
        }	
        ?>

    </div>
<div>
<?php
    echo \yii\widgets\LinkPager::widget([
        'pagination'=>$dataProvider->pagination,
    ]);?> 
</div>
<?php Pjax::end() ?>
</div>
<div style="display:none" align="center" id="loader_img" ><img src="<?= Yii::$app->homeUrl?>web/images/loaders/loading.gif"></div>
	
</div>
<div class="modal fade" id="likeModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
      <div class="modal-content" style="width: 80%; margin: auto;">
      <div class="modal-header">
        <a href="#" class="closeModal pull-right">&times;</a>
      </div>
      <div class="modal-body">
          
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
	$(document).on('click', '.deletecheck', function(){ 
		var checkmsg = confirm("Are Sure To Delete this Happy Story ?");	
		if(checkmsg == false)
		{
			return false;
		}	
		var id = $(this).attr('for');
		$.ajax({
			url : '<?=Url::to(['happy-stories/delete'])?>',
			type: 'POST',
			data: { id:id },
			success:function(data){
				location.reload();
			}
		});
	});
  $(window).on('load', function () {
    // Handler for .ready() called.
    $('html, body').animate({
        scrollTop: $('#scroll-evt').offset().top - 100
    }, 'slow');
});
var Wish    =   {
    ajax    :   false
};
$(document).on('click', '.likesView', function(){
            var val =   $(this).find('span').html();
            if(val <= 0)
                return false;
            
            var wish_id = $(this).data('id');
            if($.trim(wish_id) !== "" )
            {
                if(Wish.ajax)
                    return false;
                
                Wish.ajax   =   true;
                
                $.ajax({
                    url : '<?=Url::to(['happy-stories/likes-view'])?>',
                    type: 'GET',
                    data: {w_id:wish_id},
                    success:function(data){
                        if(data)
                        {
                            var tpl =   '';
                            var items   =   JSON.parse(data);
                            $.each(items, function(k,v){
                               tpl  +=   '<div class="likeBlock"><a href="<?=\Yii::$app->homeUrl?>account/profile?id='+v.user_id+'"><img src="<?=\Yii::$app->homeUrl?>web/uploads/users/'+v.image+'" width="50px"><span>'+v.name+'</span></a></div>';
                            });
                            
                            $('.modal-body').append(tpl);
                            $('#likeModal').modal({backdrop: 'static', keyboard: false});
                            $('#likeModal').modal('show');
                            
                            $('.closeModal').on('click', function(e){
                                e.preventDefault();
                                $('.modal-body').html('');
                                $('#likeModal').modal('hide');
                            });
                        }
                    },
                    complete: function(){
                        Wish.ajax   =   false;
                    }
                });
            }
        });
	
</script>	

web/views/happy-stories/story_full.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\UserProfile;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model app\models\Editorial */

$profile = UserProfile::find()->where(['user_id'=>$model->user_id])->one();

if(\Yii::$app->user->id == $model->user_id)	
	$this->title = 'My Happy Story';
else	
	$this->title = ucfirst($profile->firstname)."'s".' Happy Story ';

$this->params['breadcrumbs'][] = ['label' => 'Editorials', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

\Yii::$app->view->registerMetaTag([
            'name' => 'og:title',
            'property' => 'og:title',
            'content' =>$model->story_title
]);
\Yii::$app->view->registerMetaTag([
        'name' => 'og:description',
        'property' => 'og:description',
        'content' =>$model->story_text
]);
\Yii::$app->view->registerMetaTag([
        'name' => 'og:image',
        'property' => 'og:image',
        'content' =>Url::to(['web/'.$model->story_image],true)
]);

$class  =   '';	

if($model->likesCount > 0)
    $class    =   'likesView';
?>

<div class="wish-view">
    <div class="container my-profile">
	<div class="col-md-12 smp-mg-bottom">
            <?php if (Yii::$app->session->hasFlash('success_happystory')): ?>
            <div class="alert alert-success" style="margin-top: 20px;">
                Your Story has been Updated Successfully.	
            </div>
            <?php endif; ?>	
            <h3 class="smp-mg-bottom fnt-skyblue"><?=$this->title?></h3>
	
            <div class="col-md-3 happystory sharefull-list">
                <img src="<?=Yii::$app->homeUrl?>web/<?php echo $model->story_image; ?>"   class="img-responsive" alt="my-profile-Image"><br>
                <p><span data-id="<?= $model->hs_id?>" class="<?php echo $class ?>"> <span id="likecmt_<?= $model->hs_id ?>">  <?=$model->likesCount?> </span> <?php echo $model->likesCount > 1 ? 'Loves' : 'Love'; ?></span> &nbsp;
                 
                    <?php

                      if(!$model->isLiked(\Yii::$app->user->id))
                            echo  '<span title="Like it" data-w_id="'.$model->hs_id.'" data-a_type="like" class="like-wish glyphicon glyphicon-heart txt-smp-pink"></span>';
                      else
                            echo  '<span title="You liked it" data-w_id="'.$model->hs_id.'" data-a_type="like" class="like-wish glyphicon glyphicon-heart txt-smp-pink" style="color:#B23535;"></span>';
                    ?>
                    <!--<i class="fa fa-save txt-smp-orange"></i> &nbsp;
                    <i class="fa fa-thumbs-o-up txt-smp-green"></i>--> 

                    <span title="Share it" data-placement="top"  data-popover-content=""><img data-placement="top" class="listesinside"  src="<?= Yii::$app->homeUrl ?>web/images/Share-Icon.png"  /></span>					
                    <div class="shareIcons hide" data_text="<?= $model->story_title ?>" data_url="<?= Url::to(['happy-stories/story-details','id'=>$model->hs_id],true)?>" ></div>

                </p>
                    <!--<div class="shareIcons" data_text="Happy Story" data_url="<?= Url::to(['happy-stories/story-details','id'=>$model->hs_id],true)?>" ></div>-->
            </div>
            <div class="col-md-8">
                <h4 class="media-heading"><?= $model->story_title; ?></h4>
                <p><?php echo Html::a('Author: '.$profile->fullname, ['account/profile', 'id' => $model->user_id])?> <?php echo $model->story_text; ?> </p>
                <?php if(\Yii::$app->user->id == $model->user_id){ ?>
                     <?= Html::a('<i class="glyphicon glyphicon-pencil" aria-hidden="true"></i> Update', ['update', 'id' => $model->hs_id], ['class' => 'btn btn-warning ']) ?>
                     <?= Html::a('<i class="glyphicon glyphicon-trash" aria-hidden="true"></i> Delete', ['delete', 'id' => $model->hs_id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => 'Are you sure you want to delete this item?',
                        'method' => 'post',
                        ]
                    ]) ?>

                      <!--<button class="btn btn-danger deletecheck" for="<?= $model->hs_id ?>" ><i class="glyphicon glyphicon-trash" aria-hidden="true"></i> Delete </button>-->		 
                <?php } ?>
                <a class="btn btn-success" id="back">Back</a>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="likeModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
      <div class="modal-content" style="width: 80%; margin: auto;">
      <div class="modal-header">
        <a href="#" class="closeModal pull-right">&times;</a>
      </div>
      <div class="modal-body">
          
      </div>
    </div>
  </div>
</div>
<script type="text/javascript" >

$(document).ready(function(){
        $('#back').on('click', function(){
            window.location.href =   document.referrer;
        });
	$(".shareIcons").each(function(){
		var elem = $(this);
		elem.jsSocials({
                    showLabel: false,
                    showCount: true,
                    shares: ["facebook","googleplus", "linkedin",
                    {
                            share: "twitter",           // name of share
                            via: "simply_wishes",       // custom twitter sharing param 'via' (optional)
                            hashtags: "simplywishes,dream_come_true"   // custom twitter sharing param 'hashtags' (optional)
                    }],
                    url : elem.attr("data_url"),
                    text: elem.attr("data_text")
		});
	});
var Wish    =   {
    ajax    :   false
};
$(document).on('click', '.likesView', function(){
            var val =   $(this).find('span').html();
            if(val <= 0)
                return false;
            
            var wish_id = $(this).data('id');
            if($.trim(wish_id) !== "" )
            {
                if(Wish.ajax)
                    return false;
                
                Wish.ajax   =   true;
                
                $.ajax({
                    url : '<?=Url::to(['happy-stories/likes-view'])?>',
                    type: 'GET',
                    data: {w_id:wish_id},
                    success:function(data){
                        if(data)
                        {
                            var tpl =   '';
                            var items   =   JSON.parse(data);
                            $.each(items, function(k,v){
                               tpl  +=   '<div class="likeBlock"><a href="<?=\Yii::$app->homeUrl?>account/profile?id='+v.user_id+'"><img src="<?=\Yii::$app->homeUrl?>web/uploads/users/'+v.image+'" width="50px"><span>'+v.name+'</span></a></div>';
                            });
                            
                            $('.modal-body').append(tpl);
                            $('#likeModal').modal({backdrop: 'static', keyboard: false});
                            $('#likeModal').modal('show');
                            
                            $('.closeModal').on('click', function(e){
                                e.preventDefault();
                                $('.modal-body').html('');
                                $('#likeModal').modal('hide');
                            });
                        }
                    },
                    complete: function(){
                        Wish.ajax   =   false;
                    }
                });
            }
        });
	
	$(document).on('click', '.like-wish', function(){ 
		var s_id = $(this).attr("data-w_id");
		var type = $(this).attr("data-a_type");
		var elem = $(this);
		$.ajax({
			url : '<?=Url::to(['happy-stories/like'])?>',
			type: 'GET',
			data: {s_id:s_id,type:type},
			success:function(data){
				if(data == "added"){
					if(type=="fav"){
						elem.removeClass("txt-smp-orange");
						elem.addClass("txt-smp-blue");
					}
					if(type=="like"){
						elem.css('color', '#B23535');
						var likecmt = $("#likecmt_"+s_id).text();
						likecmt = parseInt(likecmt) + parseInt(1);
						$("#likecmt_"+s_id).text(likecmt);
					}
				}
				if(data == "removed"){
					if(type=="fav"){
						elem.addClass("txt-smp-orange");
						elem.removeClass("txt-smp-blue");
					}
					if(type=="like"){
						elem.css('color', '#fff');
						var likecmt = $("#likecmt_"+s_id).text();
						likecmt = parseInt(likecmt) - parseInt(1);
						$("#likecmt_"+s_id).text(likecmt);
					}
				}
			}
		});
	});
	
	$(document).on('click', '.deletecheck', function(){ 
		var checkmsg = confirm("Are Sure To Delete this Happy Story ?");	
		if(checkmsg == false)
		{
			return false;
		}
		
		var id = $(this).attr('for');
		$.ajax({
			url : '<?=Url::to(['happy-stories/delete'])?>',
			type: 'POST',
			data: { id:id },
			success:function(data){
				window.location.href = "<?= Url::to('my-story')?>"
			}
		});
		
	}); 
	
	
});

 
	
	/*		
	$(document).on('click', '.deletecheck', function(){ 
		if(confirm("Are Sure To Delete this Happy Story ?"))	
		else
			return false;		
	});
	
	
	 */
	
</script>

<script>
var isVisible = false;
var clickedAway = false;

$(document).ready(function(){	
	$(function(){
		$('.listesinside').popover({   
			html: true,
			content: function () {
				var clone = $($(this).parents(".sharefull-list").find(".shareIcons")).clone(true).removeClass('hide');
				return clone;
			}
		}).click(function(e) {
			e.preventDefault();
			clickedAway = false;
			isVisible = true;
		});
	});
	
/* 	$(document).on('click','.jssocials-shares',function(){
		 $('.listesinside').popover('hide');
	}); */
	
$(document).click(function (e) {
    if (isVisible & clickedAway) {
        $('.listesinside').popover('hide');
        isVisible = clickedAway = false;
    } else {
        clickedAway = true;
    }
});

$('body').on('hidden.bs.popover', function (e) {
    $(e.target).data("bs.popover").inState.click = false;
});

});
</script>